apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-analyzer
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/kubernetes/Desktop/volumes_analyzer-new
